tests:
  - "can build nginx-test":
      command: cd src/endtoend-test/context/docker && docker build -t nginx-test -f ./src/endtoend-test/context/docker/Dockerfile .
  - "can run nginx-test":
      command: titan run nginx-test
  - "can remove nginx-test":
      command: titan rm -f nginx-test
  - "can run nginx-test with env":
      command: titan run nginx-test -e TEST=true
  - "verify env value in nginx-test":
      command: curl -L http://localhost
      stdout:
        contains: TEST=true
  - "can remove nginx-test with env":
      command: titan rm -f nginx-test
  - "can run nginx-test without port mapping":
      command: titan run nginx-test -P
  - "verify localhost is unavailable":
      command: curl -L http://localhost
      exitValue: 7
      stderr:
        contains: "Failed to connect to localhost port 80: Connection refused"
  - "can remove nginx-test without port mapping":
      command: titan rm -f nginx-test
after:
  clearVars: true