tests:
  - "can build test container":
      command: cd src/endtoend-test/context/docker && docker build -t nginx-test -f ./src/endtoend-test/context/docker/Dockerfile .
  - "can run test container without env":
      command: titan run nginx-test
  - "can remove test container without env":
      command: titan rm -f nginx-test
  - "can run test container with env":
      command: titan run nginx-test -e TEST=true
  - "can verify env value in test container":
      command: curl -L http://localhost
      stdout:
        contains: TEST=true
  - "can remove test container with env":
      command: titan rm -f nginx-test
after:
  clearVars: true